apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: projectcontrollers.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: ProjectController
    plural: projectcontrollers
    singular: projectcontroller
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        description: ProjectController is the Schema for the projectcontrollers API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
