apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: projects.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: Project
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v2
    additionalPrinterColumns:
    - jsonPath: .spec.prefix
      name: Prefix
      type: string
    - jsonPath: .spec.githubRepo
      name: Repo
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    schema:
      openAPIV3Schema:
        description: Project is the Schema for the projects API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
