apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: projectrevisions.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: ProjectRevision
    plural: projectrevisions
    singular: projectrevision
  scope: Namespaced
  versions:
  - name: v2
    additionalPrinterColumns:
    - jsonPath: .spec.project.name
      name: Project
      type: string
    - jsonPath: .spec.ref
      name: Ref
      type: string
    - jsonPath: .spec.rev
      name: Rev
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    schema:
      openAPIV3Schema:
        description: ProjectRevision is the Schema for the projectrevisions API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
