apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: ratelimits.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: RateLimit
    plural: ratelimits
    shortNames:
    - rl
    singular: ratelimit
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: RateLimit is the Schema for the ratelimits API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
  - name: v2
    schema:
      openAPIV3Schema:
        description: RateLimit is the Schema for the ratelimits API
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
